name: Almaren Framework
on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - name : Check out repository code
        uses: actions/checkout@v2
      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql version: 13.4
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
            distribution: temurin
            java-version: 8
            cache: sbt
      - name: Build and test scala version
        run: |
          psql -c 'create database almaren;' -U postgres
          psql -c "ALTER USER postgres PASSWORD 'foo' ;"
          sbt ++2.12.10 test
          sbt ++2.13.9 test
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                              -name "*.lock"               -delete || true
